name: easyhome
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  image_picker: ^1.0.7  
  multiple_images_picker: ^1.0.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.7.0
  dio: ^5.4.1
  email_validator: '^2.1.16'
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/utils/images/logo.png
    - lib/utils/images/logo1.png
    - lib/utils/images/logo2.png
    - lib/utils/images/Mobile login-bro.png
    - lib/utils/images/Authentication-rafiki.png
    - lib/utils/images/Confirmed-bro.png
    - lib/utils/images/pageview1.png
    - lib/utils/images/pageview2.png
    - lib/utils/images/worker.png
    - lib/utils/images/photo.png
    - lib/utils/images/default.jpg
    - lib/utils/images/save-instagram.png
    - lib/utils/images/save-instagram1.png
    - lib/utils/images/web-browser.png
    - lib/utils/images/web-browser1.png
    
    

